namespace DevAgent.Worker.DotNet;

using System.Text;
using System.Xml.Linq;

/// <summary>
/// Deterministic documentation step for the DocScribe agent: generates (or
/// refreshes) <c>docs/CODEMAP.md</c> from the repository's solution/project
/// structure — projects, target frameworks, project references and package
/// references — with NO LLM involved. The optional authoring agent builds on
/// top of this map but can never replace it, so a repository always gets a
/// truthful, mechanical inventory even when no LLM is configured.
/// </summary>
public sealed class DocInventory
{
    public const string CodeMapRelativePath = "docs/CODEMAP.md";

    /// <summary>
    /// Scans <paramref name="repoPath"/> and writes docs/CODEMAP.md. Returns a
    /// mutation describing whether the file actually changed.
    /// </summary>
    public RepoMutation GenerateCodeMap(string repoPath)
    {
        var projects = Directory
            .EnumerateFiles(repoPath, "*.csproj", SearchOption.AllDirectories)
            .Where(p => !IsInsideBuildOutput(repoPath, p))
            .OrderBy(p => p, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var content = Render(repoPath, projects);

        var target = Path.Combine(repoPath, CodeMapRelativePath.Replace('/', Path.DirectorySeparatorChar));
        var before = File.Exists(target) ? File.ReadAllText(target) : null;
        if (string.Equals(before, content, StringComparison.Ordinal))
        {
            return new RepoMutation(false, "docs/CODEMAP.md is already up to date.");
        }

        Directory.CreateDirectory(Path.GetDirectoryName(target)!);
        File.WriteAllText(target, content);
        return new RepoMutation(true,
            before is null
                ? $"Created docs/CODEMAP.md covering {projects.Count} project(s)."
                : $"Refreshed docs/CODEMAP.md covering {projects.Count} project(s).");
    }

    private static bool IsInsideBuildOutput(string repoPath, string path)
    {
        var relative = Path.GetRelativePath(repoPath, path).Replace('\\', '/');
        return relative.Contains("/bin/", StringComparison.OrdinalIgnoreCase)
            || relative.Contains("/obj/", StringComparison.OrdinalIgnoreCase)
            || relative.StartsWith("bin/", StringComparison.OrdinalIgnoreCase)
            || relative.StartsWith("obj/", StringComparison.OrdinalIgnoreCase);
    }

    private static string Render(string repoPath, IReadOnlyList<string> projects)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Code map");
        sb.AppendLine();
        sb.AppendLine("> Generated by DevAgent DocScribe (deterministic inventory — no LLM).");
        sb.AppendLine("> Regenerated on every documentation run; do not edit by hand.");
        sb.AppendLine();

        var solutions = Directory
            .EnumerateFiles(repoPath, "*.sln", SearchOption.AllDirectories)
            .Where(p => !IsInsideBuildOutput(repoPath, p))
            .Select(p => Path.GetRelativePath(repoPath, p).Replace('\\', '/'))
            .OrderBy(p => p, StringComparer.OrdinalIgnoreCase)
            .ToList();
        if (solutions.Count > 0)
        {
            sb.AppendLine("## Solutions");
            sb.AppendLine();
            foreach (var sln in solutions)
            {
                sb.AppendLine($"- `{sln}`");
            }

            sb.AppendLine();
        }

        sb.AppendLine("## Projects");
        sb.AppendLine();
        if (projects.Count == 0)
        {
            sb.AppendLine("_No .csproj files found._");
        }

        foreach (var projectPath in projects)
        {
            var relative = Path.GetRelativePath(repoPath, projectPath).Replace('\\', '/');
            sb.AppendLine($"### `{relative}`");
            sb.AppendLine();

            var info = TryDescribe(projectPath, repoPath);
            if (info is null)
            {
                sb.AppendLine("_Could not parse the project file._");
                sb.AppendLine();
                continue;
            }

            if (info.TargetFrameworks.Count > 0)
            {
                sb.AppendLine($"- Target framework(s): {string.Join(", ", info.TargetFrameworks.Select(t => $"`{t}`"))}");
            }

            if (info.ProjectReferences.Count > 0)
            {
                sb.AppendLine($"- Project references: {string.Join(", ", info.ProjectReferences.Select(r => $"`{r}`"))}");
            }

            if (info.PackageReferences.Count > 0)
            {
                sb.AppendLine($"- Package references: {string.Join(", ", info.PackageReferences.Select(r => $"`{r}`"))}");
            }

            if (info.TargetFrameworks.Count == 0 && info.ProjectReferences.Count == 0 && info.PackageReferences.Count == 0)
            {
                sb.AppendLine("- (no framework/reference metadata found)");
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }

    private sealed record ProjectInfo(
        IReadOnlyList<string> TargetFrameworks,
        IReadOnlyList<string> ProjectReferences,
        IReadOnlyList<string> PackageReferences);

    private static ProjectInfo? TryDescribe(string projectPath, string repoPath)
    {
        XDocument doc;
        try
        {
            doc = XDocument.Load(projectPath);
        }
        catch (Exception ex) when (ex is System.Xml.XmlException or IOException)
        {
            return null;
        }

        var frameworks = doc.Descendants()
            .Where(e => e.Name.LocalName is "TargetFramework" or "TargetFrameworks")
            .SelectMany(e => e.Value.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(t => t, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var projectDir = Path.GetDirectoryName(projectPath)!;
        var projectRefs = doc.Descendants()
            .Where(e => e.Name.LocalName == "ProjectReference")
            .Select(e => e.Attribute("Include")?.Value)
            .Where(v => !string.IsNullOrWhiteSpace(v))
            .Select(v => NormalizeReference(projectDir, repoPath, v!))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(r => r, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var packageRefs = doc.Descendants()
            .Where(e => e.Name.LocalName == "PackageReference")
            .Select(e =>
            {
                var id = e.Attribute("Include")?.Value;
                var version = e.Attribute("Version")?.Value;
                return string.IsNullOrWhiteSpace(id) ? null : (version is null ? id : $"{id} {version}");
            })
            .Where(v => v is not null)
            .Select(v => v!)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(r => r, StringComparer.OrdinalIgnoreCase)
            .ToList();

        return new ProjectInfo(frameworks, projectRefs, packageRefs);
    }

    private static string NormalizeReference(string projectDir, string repoPath, string include)
    {
        var candidate = include.Replace('\\', Path.DirectorySeparatorChar).Replace('/', Path.DirectorySeparatorChar);
        try
        {
            var full = Path.GetFullPath(Path.Combine(projectDir, candidate));
            return Path.GetRelativePath(repoPath, full).Replace('\\', '/');
        }
        catch (Exception ex) when (ex is ArgumentException or PathTooLongException)
        {
            return include.Replace('\\', '/');
        }
    }
}
